apiVersion: v1
kind: Service
metadata:
  name: trivia-night-frontend
spec:
  ports:
    - port: 3000
  selector:
    app: trivia-night-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivia-night-frontend
spec:
  selector:
    matchLabels:
      app: trivia-night-frontend
  template:
    metadata:
      labels:
        app: trivia-night-frontend
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: trivia-night-frontend
          image: trivia-night-frontend
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3000

